# permissions for end users to edit aquaria.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: aquarium-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: aquarium-operator
    app.kubernetes.io/part-of: aquarium-operator
    app.kubernetes.io/managed-by: kustomize
  name: aquarium-editor-role
rules:
- apiGroups:
  - fun.tydanny.com
  resources:
  - aquaria
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - fun.tydanny.com
  resources:
  - aquaria/status
  verbs:
  - get
